export const MINUTE_IN_MILISECONDS = 60000;

export const TOKEN_EXPIRATION_TIME = 15 * MINUTE_IN_MILISECONDS;

export const HOUR_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 60;

export const DAY_IN_MILISECONDS = HOUR_IN_MILISECONDS * 24;

export const WEEK_IN_MILISECONDS = DAY_IN_MILISECONDS * 7;
